laungage: go
matrix:
  fast_finish: true
  include:
  - go: 1.12.x
    env: GO111MODULE=on
go_import_path: github.com/temp-go-dev/sample-api-gin
script:
  - pwd
  - go env
  - go install
  - go build -a -v
