dist: xenial
laungage: go
sudo: required
env:
  - GO111MODULE=on
go:
  - "1.12.x"
# install: true
go_import_path: github.com/temp-go-dev/sample-api-gin
script:
  - pwd
  - go env
  - go install -i
  - go build -v
