dist: xenial
laungage: go
sudo: required
matrix:
  fast_finish: true
  include:
  - go: 1.12.x
    env: GO111MODULE=on
# install: true
before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi
install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else make install; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi
go_import_path: github.com/temp-go-dev/sample-api-gin
script:
  - pwd
  - go env
  - go install -i
  - go build -v
