dist: xenial
laungage: go
sudo: required
env:
  - GO111MODULE=on
go:
  - "1.12.x"
# install: true
script:
  - pwd
  - go env
  - go install -i
  - ls -laR $GOPATH
  - go build -a -v -installsuffix cgo -o sample-api-gin .
